### ISSUE TITLE
Can't sign transactions with Ledger + Metamask

### ISSUE THREAD

**Issue by Web3Slimchance** [graphprotocol/mission-control-curator#12]
Several users have reported issues with signing Ledger/Metamask transactions. 
Switching to a non ledger account on metamask works.

**Comment by ghost** [comment]
This is a duplicate of #5

**Comment by Web3Slimchance** [comment]
You are right. I originally posted it on the Everest github, and forgot to check for duplicates when I "moved" it here :)
