### ISSUE TITLE
[SUGGESTION] Tokenize each of the projects as an NFT

### ISSUE THREAD

**Issue by tomafc330** [graphprotocol/mission-control-curator#138]
It would be cool to see each project that gets listed be an NFT (ERC721) that can be transferred and the metadata of the NFT be on IPFS. Just a suggestion and probably lower priority.

**Comment by yanivtal** [comment]
Interesting. Right now we're using the 1056 Identity standard which has delegate owners for ownership. Using NFTs to represent ownership is also interesting but maybe incompatible with the 1056 solution.
