### ISSUE TITLE
Suggestion : Fields for "Geographical Area" as well as "Primary Language"

### ISSUE THREAD

**Issue by Web3Slimchance** [graphprotocol/mission-control-curator#259]
It would be really helpful if we could filter projects based on "Geographical area" as well as main spoken language. 

"Geographical area" could make the Everest registry a useful tool for finding job opportunities in your area, that aligns with your visions for the future. 

"Language" would make it easier for people with limited English proficiency to find projects that are primarily using their native language to communicate.

**Comment by armandokaos** [comment]
![Captura de pantalla 2020-10-27 a la(s) 22 19 39](https://user-images.githubusercontent.com/67437605/97379054-9ea03480-18a2-11eb-8be0-9f396f65da0a.png)
