### ISSUE TITLE
New category suggestion: Exchanges

### ISSUE THREAD

**Issue by crypto-crack** [graphprotocol/mission-control-curator#270]
Suggestion to add category:
- Exchanges
with Subcategories:
- CEX - centralized exchanges (e.g. Binance)
- DEX - decentralizes exchanges (e.g. Uniswap)
- P2P - peer-to-peer exchanges (e.g. LocalBitcoin)

**Comment by yanivtal** [comment]
Good suggestion. Duplicate of https://github.com/graphprotocol/mission-control-curator/issues/90 with the addition of P2P.
