### ISSUE TITLE
Search Issue

### ISSUE THREAD

**Issue by cryptokingpin92** [graphprotocol/mission-control-curator#66]
When on the home page of Everest and you hit the search icon which enables the search bar which allows someone to search for a particular project an issue arises sometimes when you type the letter "O" and a high percentage of the times when you type "Ori"
The entire web page goes blank, this resulted in me not being able to search for a particular project  which resulted in me creating a duplicate.

![git](https://user-images.githubusercontent.com/73047566/96357757-ad7e2e80-10cd-11eb-88d5-f738b0a3ecee.JPG)

**Comment by KingZee** [comment]
This bug has been mentioned here :) https://github.com/graphprotocol/mission-control-curator/issues/9 it is currently being fixed

**Comment by cryptokingpin92** [comment]
Ok thanks kingzee
