### ISSUE TITLE
Data Fields when adding a new Project

### ISSUE THREAD

**Issue by cryptowhaler** [graphprotocol/mission-control-curator#70]
I think along with getting the website, github and twitter link, there should also be an option to add the link to the "subGraph" if that is available for the protocol.

**Comment by bobyD** [comment]
Your suggestion is similar to that was offered by @XingerZ early at #30 
Please, will be attentive and support already open issues 😊

**Comment by cryptowhaler** [comment]
Same as the issue here - https://github.com/graphprotocol/mission-control-curator/issues/30
